module.exports = {
  apps: [
    {
      name: "site",
      interpreter: "node",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      cwd: __dirname,
      env: { NODE_ENV: "production" },
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "bot",
      interpreter: "node",
      script: "node_modules/tsx/dist/cli.cjs",
      args: "--env-file=.env.local bot.ts",
      cwd: __dirname,
      env: { NODE_ENV: "production" },
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "broadcast",
      interpreter: "node",
      script: "node_modules/tsx/dist/cli.cjs",
      args: "--env-file=.env.local broadcast-worker.ts",
      cwd: __dirname,
      env: { NODE_ENV: "production" },
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "relay",
      interpreter: "node",
      script: "node_modules/tsx/dist/cli.cjs",
      args: "--env-file=.env.local relay-worker.ts",
      cwd: __dirname,
      env: { NODE_ENV: "production" },
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "tunnel",
      interpreter: "node",
      script: "node_modules/tsx/dist/cli.cjs",
      args: "--env-file=.env.local tunnel.ts",
      cwd: __dirname,
      env: { NODE_ENV: "production" },
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "maintenance",
      interpreter: "node",
      script: "maintenance-server.cjs",
      cwd: __dirname,
      env: { NODE_ENV: "production" },
      restart_delay: 3000,
      max_restarts: 10,
    },
  ],
};
